import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { PrismaClient } from '@prisma/client'
import { GetStaticProps } from 'next'
const prisma = new PrismaClient()

export async function getStaticProps() {
  const videos = await prisma.videos.findMany()
	return { props: { videos } }
}

export default function Home({videos}) {
  console.log(videos)
  return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<header>
				<h1 className={styles.title}>Video Recommendations</h1>
			</header>
			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href='https://nextjs.org'>Next.js!</a>
				</h1>
			</main>
		</div>
	)
}
