import React, {useState, useEffect} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { PrismaClient } from '@prisma/client'
import { GetStaticProps } from 'next'
import AllVideos from '../components/AllVideos'
const prisma = new PrismaClient()

export async function getStaticProps() {
  const videos = await prisma.videos.findMany()
	return { props: { videos } }
}

export default function Home({videos}) {
  return (
		<div className={styles.container}>
			<Head>
				<title>Video Recommendation</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
      <AllVideos videosData={videos} />
		</div>
	)
}
